import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "./Components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "project ",
  keywords: ["project", "nextjs", "react"],
  author: "author",
  description: "Generated by create next app",
};

// SEO (Search Engine Optimization): Metadata such as title, description, and keywords help search engines understand the content and context of a webpage. This helps improve the webpage's visibility in search engine results pages (SERPs).

// Accessibility: Metadata can include information that aids accessibility, such as alternative text for images, which screen readers use to describe visual content to users with visual impairments.

// Content Management: Metadata helps organize and manage digital content. It can include information such as creation date, last modified date, authorship details, and version numbers, making it easier to track and maintain content over time.

// Data Integration: Metadata facilitates data integration by providing structured information about data sources, formats, and relationships. This is crucial in data analytics, business intelligence, and data warehousing.

// Digital Rights Management: Metadata can include licensing information, copyright details, and usage restrictions, helping manage and enforce intellectual property rights.

// User Experience: Metadata influences how content is presented and categorized within digital platforms, improving the overall user experience by making content easier to find, navigate, and understand.

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head> <meta name="viewport" content="width=device-width, initial-scale=1" />  
    
    </head>
      <body className={inter.className}>
      <Header/>
      {children}</body>
    </html>
  );
}
